$schema: "./settings.schema.yaml"
environment: development
accounts:
  # Get from https://api.innohassle.ru/accounts/v0/tokens/generate-service-token?sub=sports-local-dev&scopes=sport&only_for_me=true
  api_jwt_token: ...
